DEEP LEARNING

Tuần 2: NUMPY, PANDAS, MATPLOTIB    

NUMPY

Là thư viện kiểu list vì numpy nhanh có nhiều hàm tích hợp dễ sử dụng cho AI
Để sd numpy thì: pip install numpy

In [41]:
import numpy as np

In [42]:
#thử tạo 1 list
my_list = [1, 2, 3]

#chuyển list thành mảng numpy
numpy_list = np.array(my_list)
type(numpy_list)  # Kết quả: numpy.ndarray

numpy.ndarray

In [43]:
#list trong python có thể hỗ trợ nhiều loại dữ liệu
my_list= [1, 'hello', 2.0, True]

In [44]:
my_list = [1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list  # Kết quả: dtype('int64')

array([1, 2, 3, 4, 5])

In [45]:
my_list_int = np_list.astype(int)
my_list_int

array([1, 2, 3, 4, 5])

In [46]:
#accessing và indexing
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
#lấy số 4
x[3]

np.int64(4)

In [48]:
x [0:3]

array([1, 2, 3])

In [49]:
# lấy từ 3 tới 8 theo 3 cách
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [50]:
x[-6:]

array([3, 4, 5, 6, 7, 8])

In [51]:
x[2:]

array([3, 4, 5, 6, 7, 8])

In [52]:
x[2], x[4]

(np.int64(3), np.int64(5))

In [53]:
#đặt danh sách index muốn truy cập
x[[2,4]]

array([3, 5])

In [54]:
data = [[1, 2], [3, 4], [5, 6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np_list[0, 1]  # Kết quả: 2

np.int64(2)

In [56]:
np_list[2, 1]

np.int64(6)

In [57]:
#lấy từ 3 tới 6
np_list[2, 1]

np.int64(6)

In [58]:
#C2
np_list[[1, 2]]

array([[3, 4],
       [5, 6]])

In [59]:
#C3
np_list[1:3, 0:2]

array([[3, 4],
       [5, 6]])

In [60]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [61]:
np_list[:, 0]

array([1, 3, 5])

In [62]:
np_list[0, 0], np_list[1, 0], np_list[2, 0]

(np.int64(1), np.int64(3), np.int64(5))

In [63]:
np_list[[0, 2], 0]

array([1, 5])

In [64]:
np.array([np_list[0, 0], np_list[2, 0]])

array([1, 5])

In [65]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)

In [66]:
np_list[:, 1]

array([ 2,  6, 10, 14])

In [67]:
np_list[1:3, 2]

array([ 7, 11])

In [68]:
np_list[0:3, 3]

array([ 4,  8, 12])

In [69]:
np_list[[0,1,2], [3,2,1]]

array([ 4,  7, 10])

In [70]:
np_list[-1, :: -1]

array([16, 15, 14, 13])

#BTVN thú vị
#cho ma trận = [[99,99,99],
#               [99,99,99],
#               [99,99,99]]

#hãy tưởng tượng ô 99 trống
#giả sử 1 là x
#giả sử 0 là o

#lấy đầu vào từ phía x và phí 0 luân phiên
#nếu đầu vào từ phía x là (0,0)

#ma trận sẽ trở thành
#              [[x,99,99],
#               [99,99,99],
#               [99,99,99]]
# nếu đầu vào từ phía 0 là (0,0)
# Thông báo họ nhập lại
# nếu không thì điền vào ma trận
# thử thách: nếu người chơi đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi 

BTVN2:
Cho y = [[1,2,3],
        [4,5,6],
        [7,8,9]]

lấy 4 5 6
lấy 2 5
lấy 3 4
lấy 9 6 3

BTVN3:
x=[1,2,3,4,5,6,7,8,9,10]
1.xuất ra các giá trị chẵn theo sử dụng if
2.xuất ra các giá trị chẵn theo sử dụng list comprehension

In [71]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np_x[np_x %2 == 0]

array([0, 2, 4, 6, 8])

In [75]:
np_x %2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [76]:
idx = [ True, True,  True, False,  True, True,  True, False,  True,
       True]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8, 9])

In [77]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
cond1 = np_x %2 != 0
cond2 = np_x>5
cond3 = np_x >0
np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# BTVN 
# Tao mot mang numpy co kich thuoc 150x5. Gia su mang nay chua 150 mau du lieu 
# cua sinh vien bao gom chieu cao can nang , tuoi , luong va diem tb 
# Tach mang dua tren 4 cot dau tien thanh 1 bien co ten la X va cot cuoi cung thanh Y 
# Tach X thanh X_train va X_test trong do X_train chua 70 % du lieu va tach Y thanh Y_train va Y_test 
# Trong do Y_trai chua 70% du lieu  

#  Tao 10 tap du lieu X_trai khong chong  cheo nhau 