DEEP LEARNING

Tuần 2: NUMPY, PANDAS, MATPLOTIB    

NUMPY

Là thư viện kiểu list vì numpy nhanh có nhiều hàm tích hợp dễ sử dụng cho AI
Để sd numpy thì: pip install numpy

In [20]:
import numpy as np

In [21]:
#thử tạo 1 list
my_list = [1, 2, 3]

#chuyển list thành mảng numpy
numpy_list = np.array(my_list)
type(numpy_list)  # Kết quả: numpy.ndarray

numpy.ndarray

In [22]:
#list trong python có thể hỗ trợ nhiều loại dữ liệu
my_list= [1, 'hello', 2.0, True]

In [23]:
my_list = [1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list  # Kết quả: dtype('int64')

array([1, 2, 3, 4, 5])

In [24]:
my_list_int = np_list.astype(int)
my_list_int

array([1, 2, 3, 4, 5])

In [25]:
#accessing và indexing
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
#lấy số 4
x[3]

np.int64(4)

In [27]:
x [0:3]

array([1, 2, 3])

In [ ]:
# lấy từ 3 tới 8 theo 3 cách
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [32]:
x[-6:]

array([3, 4, 5, 6, 7, 8])

In [33]:
x[2:]

array([3, 4, 5, 6, 7, 8])

In [34]:
x[2], x[4]

(np.int64(3), np.int64(5))

In [35]:
#đặt danh sách index muốn truy cập
x[[2,4]]

array([3, 5])

In [36]:
data = [[1, 2], [3, 4], [5, 6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np_list[0, 1]  # Kết quả: 2

np.int64(2)

In [39]:
np_list[2, 1]

np.int64(6)

In [ ]:
#lấy từ 3 tới 6
np_list[2, 1]

np.int64(6)

In [ ]:
#C2
np_list[[1, 2]]

array([[3, 4],
       [5, 6]])

In [ ]:
#C3
np_list[1:3, 0:2]

array([[3, 4],
       [5, 6]])

In [45]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [46]:
np_list[:, 0]

array([1, 3, 5])

In [47]:
np_list[0, 0], np_list[1, 0], np_list[2, 0]

(np.int64(1), np.int64(3), np.int64(5))

In [48]:
np_list[[0, 2], 0]

array([1, 5])

In [49]:
np.array([np_list[0, 0], np_list[2, 0]])

array([1, 5])

In [50]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)

In [51]:
np_list[:, 1]

array([ 2,  6, 10, 14])

In [52]:
np_list[1:3, 2]

array([ 7, 11])

In [53]:
np_list[0:3, 3]

array([ 4,  8, 12])

In [54]:
np_list[[0,1,2], [3,2,1]]

array([ 4,  7, 10])

In [55]:
np_list[-1, :: -1]

array([16, 15, 14, 13])

#BTVN thú vị
#cho ma trận = [[99,99,99],
#               [99,99,99],
#               [99,99,99]]

#hãy tưởng tượng ô 99 trống
#giả sử 1 là x
#giả sử 0 là o

#lấy đầu vào từ phía x và phí 0 luân phiên
#nếu đầu vào từ phía x là (0,0)

#ma trận sẽ trở thành
#              [[x,99,99],
#               [99,99,99],
#               [99,99,99]]
# nếu đầu vào từ phía 0 là (0,0)
# Thông báo họ nhập lại
# nếu không thì điền vào ma trận
# thử thách: nếu người chơi đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi 

BTVN2:
Cho y = [[1,2,3],
        [4,5,6],
        [7,8,9]]

lấy 4 5 6
lấy 2 5
lấy 3 4
lấy 9 6 3

BTVN3:
x=[1,2,3,4,5,6,7,8,9,10]
1.xuất ra các giá trị chẵn theo sử dụng if
2.xuất ra các giá trị chẵn theo sử dụng list comprehension

In [57]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])